---
###############################################################################
# docker-install.yml
#     install the docker components and enablements
#
###############################################################################

# Update the apt repository
- name: Update repositories cache
  apt:
    update_cache: yes
  tags:
    - install-docker

- name: Install Pre-req Packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  tags:
    - install-docker

- name: Add GPG signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - install-docker

- name: Add docker repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags:
    - install-docker

- name: Install Docker Engine
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    update_cache: yes
  tags:
    - install-docker

- name: Install Python Docker Library
  pip:
    name: docker-py

# update the user to use Docker
- name: Update the "{{ myuser }}" user to use Docker
  user:
    name: "{{ myuser }}"
    groups: docker
    append: yes
  tags:
    - install-docker
