---
debug: 0
ansible_python_interpreter: /usr/bin/python3
ansible_user: gdavis
#ansible_ssh_pass: frankie

myuser: gdavis
domain: aqua.lab         # Domain Name to use in your Environment
net_prefix: 192.168.5        # Your Network Subnet to use
subnet: 192.168.5.0         # Your Network Subnet to use
submask: 255.255.255.0       # Your Network Subnet to use
gateway: 192.168.5.1       # Gateway to use and Vyos Internal IP
dns: 192.168.5.30               # DNS Server for your Internal Network
ntp: 192.168.5.30               # DNS Server for your Internal Network
global_dns: 8.8.8.8 # External DNS
password_common: VMware1!   # Password to be shared - feel free to overwrite below
dc_name: k8s-DC1
dc_ip: 192.168.5.30
vcsa_name: vcsa
vcsa_ip: 192.168.5.10
esxi1_name: esxi01
esxi1_ip: 192.168.5.11
esxi2_name: esxi02
esxi2_ip: 192.168.5.12

#LDAP Variables
ldap_root: dc=aqua,dc=lab
ldap_admin_username: manager
ldap_admin_password: VMware1!
ldap_users: user01,user02
ldap_passwords: password1,password2

image: 
  dnsmasq: "jpillora/dnsmasq:1.1.0"
  ntp: "cloudwattfr/ntpserver"
#  ntp: "jenkins/jenkins:2.263.4-lts-centos7"
  ldap: "bitnami/openldap:2.4.57"