---
ansible_python_interpreter: /usr/bin/python3

myuser: gdavis

domain: "davis.home"         # Domain Name to use in your Environment
net_prefix: "192.168.60"     # Your Network Subnet to use
subnet: "192.168.60.0"       # Your Network Subnet to use
submask: "255.255.255.0"     # Your Network Subnet to use
gateway: "192.168.60.1"      # Gateway to use and Vyos Internal IP
dns: "192.168.60.9"          # DNS Server for your Internal Network
ntp: "192.168.60.9"          # DNS Server for your Internal Network
global_dns: "8.8.8.8"        # External DNS
password_common: "VMware1!"  # Password to be shared - feel free to overwrite below
dc_name: "dc-60-9"
dc_ip: "{{ dns }}"
vcsa_name: "vcsa"
vcsa_ip: "192.168.60.10"
esxi1_name: "esxi01"
esxi1_ip: "192.168.60.11"
esxi2_name: "esxi02"
esxi2_ip: "192.168.60.12"

#LDAP Variables
ldap_root: dc=davis,dc=home
ldap_admin_username: manager
ldap_admin_password: VMware1!
ldap_users: user01,user02
ldap_passwords: password1,password2
