pipeline {

    agent any

    environment {
        PIPELINE_REPO = "https://github.com/davisglenn/aqua-build-dc.git"
        PIPELINE_BRANCH = "main"
        PIPELINE_WORKSPACE = "/var/lib/jenkins/workspace/Build_Domain_Controller"
        }


stages {

      stage('Install Docker') {
          steps {
              script{
                  rc = sh (
                          script:  'ansible-playbook -i ${PIPELINE_WORKSPACE}/Inventories ${PIPELINE_WORKSPACE}/Pipelines/playbooks/build-dc.yml --tags=install-docker' 
                  )
              }
          }
      }
      stage('Scan DNSmasq for Vulnerabilites') {
          steps {
              script{
                  rc = sh (
                          script:  'trivy client --clear-cache=false --exit-code=1 --severity=CRITICAL --remote http://192.168.5.9:9999 jpillora/dnsmasq' 
                  )
              }
          }
      }
      stage('Create DNSmasq container') {
          steps {
              script{
                  rc = sh (
                          script:  'ansible-playbook -i ${PIPELINE_WORKSPACE}/Inventories ${PIPELINE_WORKSPACE}/Pipelines/playbooks/build-dc.yml --tags=dnsmasq' 
                  )
              }
          }
      }
      stage('Scan NTP for Vulnerabilites') {
          steps {
              script{
                  rc = sh (
                          script:  'trivy client --clear-cache=false --exit-code=1 --severity=CRITICAL --remote http://192.168.5.9:9999 alpine:3.10' 
                  )
              }
          }
      }
      stage('Create NTP container') {
          steps {
              script{
                  rc = sh (
                          script:  'ansible-playbook -i ${PIPELINE_WORKSPACE}/Inventories ${PIPELINE_WORKSPACE}/Pipelines/playbooks/build-dc.yml --tags=ntp' 
                  )
              }
          }
      }
      stage('Scan LDAP for Vulnerabilites') {
          steps {
              script{
                  rc = sh (
                          script:  'trivy client --clear-cache=false --exit-code=1 --severity=CRITICAL --remote http://192.168.5.9:9999 bitnami/openldap' 
                  )
              }
          }
      }
      stage('Create LDAP container') {
          steps {
              script{
                  rc = sh (
                          script:  'ansible-playbook -i ${PIPELINE_WORKSPACE}/Inventories ${PIPELINE_WORKSPACE}/Pipelines/playbooks/build-dc.yml --tags=ldap'
                  )
              }
          }
      }
  }
}
