pipeline {

    agent any

    environment {
        PIPELINE_REPO = "https://github.com/davisglenn/aqua-build-dc.git"
        PIPELINE_BRANCH = "main"
        PIPELINE_WORKSPACE = "/var/lib/jenkins/workspace/Build\ Domain\ Controller"
        }

stages {

      stage('Install Docker') {
          steps {
              script{
                  rc = sh (
                          script:  'ansible-playbook -i ${PIPELINE_WORKSPACE}/Inventories ${PIPELINE_WORKSPACE}/Pipelines/playbooks/build-dc.yml --tags=install-docker' 
                  )
                  echo "The command line return code is: ${rc}"
              }
          }
      }
      stage('Create DNSmasq container') {
          steps {
              script{
                  rc = sh (
                          script:  'echo Create DNSmasq container'
                  )
                  echo "The command line return code is: ${rc}"
              }
          }
      }
      stage('Create NTP container') {
          steps {
              script{
                  rc = sh (
                          script:  'echo Create NTP container'
                  )
                  echo "The command line return code is: ${rc}"
              }
          }
      }
      stage('Create LDAP container') {
          steps {
              script{
                  rc = sh (
                          script:  'echo Create LDAP container'
                  )
                  echo "The command line return code is: ${rc}"
              }
          }
      }
  }
}
