---
# Domain Controller Provisioner Inventory
all:
  children:
    windows:
      hosts:
        192.168.5.2:
    dc:
      hosts:
        192.168.5.30:
    vcsa:
      hosts:
        192.168.5.10:
    esxi:
      hosts:
        192.168.5.11:
        192.168.5.12:

